id: P010555
initial_creation_type: ocr
source_metadata:
  id: bdr:W23949
  title: རྗེ་གྲུབ་པའི་དབང་ཕྱུག་ངག་དབང་བསམ་གཏན་གྱི་རྣམ་པར་ཐར་པ་སྐལ་བཟང་བུང་བ་དགའ་བྱེད་ཨུཏཔལ་དཀར་པོའི་འཁྲི་ཤིང
  author: ''
  volumes:
    9787afe16e4741c1bfbfc556c67f5cd2:
      image_group_id: I3585
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
