id: opecha:P010555
initial_creation_type: ocr
source_metadata:
  id: bdr:W23949
  title: རྗེ་གྲུབ་པའི་དབང་ཕྱུག་ངག་དབང་བསམ་གཏན་གྱི་རྣམ་པར་ཐར་པ་སྐལ་བཟང་བུང་བ་དགའ་བྱེད་ཨུཏཔལ་དཀར་པོའི་འཁྲི་ཤིང
  volume: ''
  author: ''
