id: I7C8BD294
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:01:38+00:00'
last_modified: '2022-06-08T14:27:40.997082+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23949
  title: རྗེ་གྲུབ་པའི་དབང་ཕྱུག་ངག་དབང་བསམ་གཏན་གྱི་རྣམ་པར་ཐར་པ་སྐལ་བཟང་བུང་བ་དགའ་བྱེད་ཨུཏཔལ་དཀར་པོའི་འཁྲི་ཤིང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    092C:
      image_group_id: I3585
      title: ''
      total_pages: 130
      order: 1
      base_file: 092C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
